spring:
  data:
    mongodb:
      username: ecommerce
      password: ecommerce
      host: localhost
      port: 27017
      database: ecom_notification
      authentication-database: admin

    kafka:
      consumer:
        bootstrap-servers: localhost:9092
        group-id: paymentGroup,orderGroup
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.trusted.packages: '*'
          spring.json.type.mapping: orderConfirmation:com.ecommerce.notification.kakfa.order.OrderConfirmation,paymentConfirmation:com.ecommerce.notification.kakfa.payment.PaymentNotification
    mail:
      host: localhost
      port: 1025
      username: admin
      password: admin
      properties:
        mail:
          smtp:
            trust: "*"
          auth: true
            starttls:
              enabled: true
            connectiontimeout: 5000
            timeout: 3000
            writetimeout: 5000

server:
  port: 8084